name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4

      - name: 📂 FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ftpupload.net
          username: if0_42297225
          password: zgbGSOdQNMrhcud

          
          server-dir: /htdocs/

          dangerous-clean-slate: true